[package]
name = "apathetic-trading-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binance =  "0.20.2"
dotenv = "0.15.0"
ta = "0.5.0"
